#!/usr/bin/env python3
"""Generate the Mintlify documentation site (docs/site/) from surface.json.

surface.json is the single source of truth for the Tempera SDK: products,
audiences, scopes, environment targets, the error contract, every typed
operation, and the MCP gateway. This script renders it (plus docs/ROLLOUT.md
for the rollout page) into a complete Mintlify project:

  docs/site/docs.json                    Mintlify config + navigation
  docs/site/index.mdx                    overview, quickstart, product table
  docs/site/authentication.mdx           OAuth2 + PKCE, tp_ keys, audiences, scopes
  docs/site/environments.mdx             environment presets + base-URL precedence
  docs/site/errors.mdx                   TemperaApiError, wire shapes, MCP errors
  docs/site/mcp-gateway.mdx              unified MCP gateway
  docs/site/rollout.mdx                  rendered from docs/ROLLOUT.md
  docs/site/products/<product>.mdx       one page per typed product, every operation
  docs/site/products/other-products.mdx  registry-only products + request() escape hatch

The generated site is committed; scripts/check-sdk-surface.py re-renders it
and fails on any diff, so the docs cannot drift from the manifest. Rendering
is deterministic: sorted iteration for derived aggregates, no timestamps.

Usage:
  python3 scripts/gen-sdk-docs.py           # write docs/site/ (removes strays)
  python3 scripts/gen-sdk-docs.py --check   # exit 1 if docs/site/ is stale
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SURFACE = ROOT / "surface.json"
ROLLOUT = ROOT / "docs" / "ROLLOUT.md"
SITE = ROOT / "docs" / "site"

GENERATED_NOTE = (
    "{/* Generated by scripts/gen-sdk-docs.py from surface.json -- do not hand-edit. */}"
)

OVERVIEW_PAGES = ["index", "authentication", "environments", "errors", "mcp-gateway", "rollout"]

# Meanings for the MCP gateway JSON-RPC error codes (keyed by surface.json name).
MCP_ERROR_MEANINGS = {
    "planLimit": "Plan limit exceeded (`plan_limit_exceeded`): the workspace's metered "
    "`mcp_invocations` allowance is exhausted; upgrade the plan or wait for the meter to reset.",
    "invalidRequest": "The payload is not a valid JSON-RPC 2.0 request.",
    "methodNotFound": "Unknown JSON-RPC method (or unknown tool name on `tools/call`).",
    "invalidParams": "The method was called with invalid or missing parameters.",
    "internalError": "The gateway or an upstream product MCP server failed.",
}


def snake(camel: str) -> str:
    """lowerCamelCase -> snake_case (matches gen-sdk-surface.py and the Rust keys)."""
    return re.sub(r"(?<!^)(?=[A-Z])", "_", camel).lower()


def snake_attr(camel: str) -> str:
    """lowerCamelCase -> snake_case as the Python client's attribute names do
    (consecutive capitals stay one word: tempOS -> temp_os)."""
    return re.sub(r"([a-z0-9])([A-Z]+)", r"\1_\2", camel).lower()


def kebab(camel: str) -> str:
    return re.sub(r"(?<!^)(?=[A-Z])", "-", camel).lower()


def esc(text: str) -> str:
    """Escape prose for MDX: literal braces and '<' would otherwise start JSX."""
    return (
        text.replace("\\", "\\\\")
        .replace("{", "\\{")
        .replace("}", "\\}")
        .replace("<", "\\<")
    )


def cell(text: str) -> str:
    """Escape prose for a Markdown table cell."""
    return esc(text).replace("|", "\\|")


def frontmatter(title: str, description: str) -> str:
    return "\n".join(
        [
            "---",
            f"title: {json.dumps(title)}",
            f"description: {json.dumps(description)}",
            "---",
            "",
            GENERATED_NOTE,
            "",
        ]
    )


def private_access_note() -> list[str]:
    return [
        "> **Private access.** Hosted Tempera services are available through design-partner onboarding.",
        "> Use the issuer, credentials, environment, and product URLs provisioned for your workspace;",
        "> start in staging unless Tempera explicitly approves another target.",
        "",
    ]


def code_group(blocks: list[tuple[str, str, str]]) -> list[str]:
    """A Mintlify <CodeGroup> from (language, tab title, code) blocks."""
    lines = ["<CodeGroup>", ""]
    for language, title, code in blocks:
        lines.append(f"```{language} {title}")
        lines.append(code.rstrip("\n"))
        lines.append("```")
        lines.append("")
    lines.append("</CodeGroup>")
    lines.append("")
    return lines


def typed_products(surface: dict) -> list[str]:
    return [key for key in surface["products"] if key in surface["operations"]]


def registry_products(surface: dict) -> list[str]:
    return [key for key in surface["products"] if key not in surface["operations"]]


def product_page_slug(product_key: str) -> str:
    return f"products/{kebab(product_key)}"


def auth_label(surface: dict, product_key: str, op: dict) -> str:
    kind = op["auth"]
    if kind == "none":
        return "None (public endpoint)."
    if kind == "account":
        return "Account bearer — the control-plane session token stored by `login`/`signup`."
    if kind == "introspectionSecret":
        return "Introspection secret bearer (server-side only)."
    audience = surface["products"][product_key]["audience"] or surface["defaultAudience"]
    return f"Product bearer — an access token minted for audience `{audience}`, or a central `tp_` API key."


def example_param_names(op: dict) -> list[str]:
    """Parameters shown in the per-operation example: every path parameter,
    plus a readable sample of the declared query/body parameters."""
    names = list(op.get("pathParams", []))
    if op["method"] in ("GET", "DELETE"):
        names += op.get("query", [])[:2]
    else:
        names += op.get("body", [])[:3]
    return names


def operation_example(surface: dict, product_key: str, op: dict) -> list[str]:
    names = example_param_names(op)
    ts_attr = product_key
    py_attr = snake_attr(product_key)
    rust_product = snake(product_key)
    op_snake = snake(op["id"])

    if names:
        ts_args = "{\n" + "".join(f'  {name}: "<{name}>",\n' for name in names) + "}"
        ts_code = f"const result = await client.{ts_attr}.{op['id']}({ts_args});"
        py_args = "{\n" + "".join(f'    "{name}": "<{name}>",\n' for name in names) + "}"
        py_code = f"result = client.{py_attr}.{op_snake}({py_args})"
        rust_args = "&[\n" + "".join(f'    ("{name}", "<{name}>".into()),\n' for name in names) + "]"
    else:
        ts_code = f"const result = await client.{ts_attr}.{op['id']}();"
        py_code = f"result = client.{py_attr}.{op_snake}()"
        rust_args = "&[]"
    rust_code = (
        f'let spec = client.build_request("{rust_product}", "{op_snake}", {rust_args})?;\n'
        "// Send spec.method / spec.full_url() / spec.headers / spec.body_json\n"
        "// with your own HTTP client."
    )
    return code_group(
        [
            ("typescript", "TypeScript", ts_code),
            ("python", "Python", py_code),
            ("rust", "Rust", rust_code),
        ]
    )


def param_table(title: str, rows: list[tuple[str, str, str]]) -> list[str]:
    lines = [f"**{title}**", "", "| Parameter | Required | Notes |", "|---|---|---|"]
    for name, required, notes in rows:
        lines.append(f"| `{name}` | {required} | {notes or '—'} |")
    lines.append("")
    return lines


def operation_section(surface: dict, product_key: str, op: dict) -> list[str]:
    op_snake = snake(op["id"])
    rust_product = snake(product_key)
    lines = [f"### {op['id']}", ""]
    lines.append(f"`{op['method']} {op['path']}`")
    lines.append("")
    lines.append(esc(op["description"]))
    lines.append("")
    lines.append(f"- **Auth:** {auth_label(surface, product_key, op)}")
    if op.get("scope"):
        lines.append(f"- **Scope:** `{op['scope']}`")
    lines.append(
        f"- **Call as:** TypeScript `client.{product_key}.{op['id']}()` · "
        f"Python `client.{snake_attr(product_key)}.{op_snake}()` · "
        f'Rust `build_request("{rust_product}", "{op_snake}", params)`'
    )
    lines.append("")

    defaults = op.get("bodyDefaults", {})
    if op.get("pathParams"):
        lines += param_table(
            "Path parameters",
            [(name, "yes", "Substituted into the URL path (percent-encoded).") for name in op["pathParams"]],
        )
    if op.get("query"):
        lines += param_table("Query parameters", [(name, "no", "") for name in op["query"]])
    body_rows: list[tuple[str, str, str]] = []
    for name in op.get("body", []):
        note = ""
        if name in defaults:
            note = f"Defaults to `{json.dumps(defaults[name])}` when omitted."
        body_rows.append((name, "no", note))
    for name in sorted(set(defaults) - set(op.get("body", []))):
        body_rows.append(
            (name, "always sent", f"Included automatically as `{json.dumps(defaults[name])}`; pass `{name}` to override.")
        )
    if body_rows:
        lines += param_table("Body parameters", body_rows)
    lines += operation_example(surface, product_key, op)
    return lines


def render_docs_json(surface: dict) -> str:
    config = {
        "$schema": "https://mintlify.com/docs.json",
        "theme": "mint",
        "name": "Tempera SDK",
        "colors": {"primary": "#0D9373", "light": "#07C983", "dark": "#0D9373"},
        "navigation": {
            "groups": [
                {"group": "Overview", "pages": OVERVIEW_PAGES},
                {
                    "group": "API Reference",
                    "pages": [product_page_slug(key) for key in typed_products(surface)],
                },
                {"group": "Registry", "pages": ["products/other-products"]},
            ]
        },
        "footer": {
            "socials": {"github": "https://github.com/tempera-dev/tempera-sdk"}
        },
    }
    return json.dumps(config, indent=2) + "\n"


def render_index(surface: dict) -> str:
    lines = [
        frontmatter(
            "Tempera SDK",
            "One SDK, three languages, every Tempera product — generated from a single manifest.",
        )
    ]
    lines += [
        "The Tempera SDK exposes **one uniform surface in three languages** — TypeScript",
        "(`@tempera/sdk`), Python (`tempera-sdk`), and Rust (`tempera-sdk`) — covering every",
        "Tempera product: the same product registry, the same operation names and",
        "descriptions, and the same error model. All of it is generated from a single",
        "manifest, `surface.json`, and gated in CI so the packages (and these docs)",
        "cannot drift apart.",
        "",
    ]
    lines += private_access_note()
    lines += [
        "## Quickstart",
        "",
        "After private onboarding, authenticate with the issuer and API key supplied for",
        "your workspace, then call the products enabled for that workspace. These examples",
        "start with the staging preset.",
        "",
    ]
    ts_code = (
        "// Package access and environment values are supplied during onboarding.\n"
        'import { TemperaAuth, createTemperaClient } from "@tempera/sdk";\n'
        "\n"
        "const issuerUrl = process.env.TEMPERA_ISSUER_URL;\n"
        'if (!issuerUrl) throw new Error("Missing TEMPERA_ISSUER_URL");\n'
        "\n"
        "const auth = new TemperaAuth({\n"
        "  issuerUrl,\n"
        "  apiKey: process.env.TEMPERA_API_KEY, // tp_... works at every product\n"
        "});\n"
        'const client = createTemperaClient({ auth, environment: "staging" });\n'
        "\n"
        'const traces = await client.palette.listTraces({ tenant_id: "org_1", limit: 20 });\n'
        'const session = await client.tempo.createSession({ url: "https://example.com" });'
    )
    py_code = (
        "# Package access and environment values are supplied during onboarding.\n"
        "import os\n"
        "from tempera_sdk import TemperaAuth, TemperaClient\n"
        "\n"
        "auth = TemperaAuth(\n"
        '    issuer_url=os.environ["TEMPERA_ISSUER_URL"],\n'
        '    api_key=os.environ["TEMPERA_API_KEY"],  # tp_... works at every product\n'
        ")\n"
        'client = TemperaClient(auth=auth, environment="staging")\n'
        "\n"
        'traces = client.palette.list_traces({"tenant_id": "org_1", "limit": 20})\n'
        'session = client.tempo.create_session({"url": "https://example.com"})'
    )
    rust_code = (
        "// Crate access and environment values are supplied during onboarding.\n"
        "use tempera_sdk::{TemperaAuth, TemperaClient};\n"
        "\n"
        "// The Rust crate is HTTP-less: it builds fully-described RequestSpecs\n"
        "// (method, URL, headers, JSON body) for your own HTTP client to send.\n"
        'let issuer_url = std::env::var("TEMPERA_ISSUER_URL")?;\n'
        'let api_key = std::env::var("TEMPERA_API_KEY")?;\n'
        "let auth = TemperaAuth::new(issuer_url).with_api_key(api_key);\n"
        "let client = TemperaClient::new().with_auth(auth);\n"
        "\n"
        "let spec = client.build_request(\n"
        '    "palette",\n'
        '    "list_traces",\n'
        '    &[("tenant_id", "org_1".into()), ("limit", 20i64.into())],\n'
        ")?;\n"
        "// spec.method / spec.full_url() / spec.headers / spec.body_json"
    )
    lines += code_group(
        [
            ("typescript", "TypeScript", ts_code),
            ("python", "Python", py_code),
            ("rust", "Rust", rust_code),
        ]
    )
    lines += [
        "Method naming is mechanical across the languages: the manifest's camelCase",
        "operation id in TypeScript (`listTraces`), snake_case in Python (`list_traces`),",
        'and `build_request(product, "list_traces", params)` in Rust. Parameters use wire',
        "names (snake_case) in every language.",
        "",
        "## Products",
        "",
        "Every product in the registry — including the ones without typed operations",
        "yet — gets a client in all three languages.",
        "",
        "| Product | Audience | Env var | Repository | Operations | Description |",
        "|---|---|---|---|---|---|",
    ]
    for key, product in surface["products"].items():
        ops = surface["operations"].get(key, [])
        if ops:
            slug = product_page_slug(key)
            name_cell = f"[{product['name']}](/{slug})"
            ops_cell = str(len(ops))
        else:
            name_cell = f"[{product['name']}](/products/other-products)"
            ops_cell = "passthrough"
        audience = f"`{product['audience']}`" if product["audience"] else "—"
        repo = product["repository"]
        repo_name = repo.rsplit("/", 1)[-1]
        lines.append(
            f"| {name_cell} | {audience} | `{product['envVar']}` | [{repo_name}]({repo}) "
            f"| {ops_cell} | {cell(product['description'])} |"
        )
    total_ops = sum(len(ops) for ops in surface["operations"].values())
    lines += [
        "",
        f"{total_ops} typed operations across {len(typed_products(surface))} products, plus a raw",
        "`request()` escape hatch on every product client for endpoints the surface",
        "tables do not cover yet.",
        "",
        "## Where to go next",
        "",
        "- [Authentication](/authentication) — the unified account model, OAuth2 + PKCE, and `tp_` API keys.",
        "- [Environments](/environments) — presets and base-URL resolution.",
        "- [Errors](/errors) — one `TemperaApiError` across six wire shapes.",
        "- [MCP gateway](/mcp-gateway) — every product as namespaced MCP tools.",
        "- [Rollout](/rollout) — how an endpoint change propagates into the SDK.",
        "",
    ]
    return "\n".join(lines)


def render_authentication(surface: dict) -> str:
    issuer = surface["issuer"]
    lines = [
        frontmatter(
            "Authentication",
            "Unified accounts, OAuth2 authorization-code + PKCE with audience selection, and tp_ API keys.",
        )
    ]
    lines += private_access_note()
    lines += [
        "## One account, every product",
        "",
        "The provisioned Tempera control plane (auth-hub) is the OAuth 2.1 issuer for the whole",
        "fleet. One Tempera account mints one access token per **product audience**,",
        "and central API keys (`tp_...`) work as bearers at every product via central",
        "introspection. The SDK's `TemperaAuth` holds both: per-audience OAuth token",
        "sets and an optional unified API key.",
        "",
        "## OAuth2: authorization code + PKCE (S256)",
        "",
        "Public clients use the authorization-code flow with PKCE",
        f"(`{issuer['pkceMethod']}` only). The audience is selected with the RFC 8707",
        "`resource` parameter on both the authorize and token requests:",
        "",
        f"1. **Authorize** — send the user to `{issuer['authorizePath']}` with",
        "   `response_type=code`, your `client_id`, a `code_challenge` (S256), and",
        "   `resource=<audience>` (plus optional `scope` and `state`).",
        f"2. **Exchange** — POST the returned code to `{issuer['tokenPath']}` with the",
        "   PKCE `code_verifier` and the same `resource`; you receive the audience's",
        "   access + refresh token set.",
        f"3. **Refresh** — POST `grant_type=refresh_token` to `{issuer['tokenPath']}`.",
        "   Refresh tokens **rotate**: the newly issued refresh token replaces the old",
        "   one in the SDK's store.",
        f"4. **Revoke** — POST the token to `{issuer['revokePath']}` to invalidate it;",
        "   the SDK drops the stored token set.",
        "",
    ]
    ts_code = (
        'import { TemperaAuth, createPkcePair } from "@tempera/sdk";\n'
        "\n"
        "const issuerUrl = process.env.TEMPERA_ISSUER_URL;\n"
        "const clientId = process.env.TEMPERA_CLIENT_ID;\n"
        'if (!issuerUrl || !clientId) throw new Error("Missing provisioned Tempera auth settings");\n'
        "\n"
        "const auth = new TemperaAuth({\n"
        "  issuerUrl,\n"
        "  clientId,\n"
        "});\n"
        "\n"
        "// 1. Authorize: PKCE S256 + RFC 8707 resource audience selector.\n"
        "const { verifier, challenge } = await createPkcePair();\n"
        "const authorizeUrl = auth.buildAuthorizeUrl({\n"
        '  redirectUri: "https://my-app.example/callback",\n'
        "  codeChallenge: challenge,\n"
        '  audience: "tempo",\n'
        '  scope: ["trace:read", "trace:write"],\n'
        "});\n"
        "\n"
        "// 2. Exchange the returned code for the audience's token set.\n"
        "await auth.exchangeCode({\n"
        "  code,\n"
        "  codeVerifier: verifier,\n"
        '  redirectUri: "https://my-app.example/callback",\n'
        '  audience: "tempo",\n'
        "});\n"
        "\n"
        "// 3. Refresh with rotation: the new refresh token replaces the old one.\n"
        'await auth.refresh("tempo");\n'
        "\n"
        "// 4. Revoke and drop the stored token set.\n"
        'await auth.revoke("tempo");'
    )
    py_code = (
        "import os\n"
        "from tempera_sdk import TemperaAuth, create_pkce_pair\n"
        "\n"
        "auth = TemperaAuth(\n"
        '    issuer_url=os.environ["TEMPERA_ISSUER_URL"],\n'
        '    client_id=os.environ["TEMPERA_CLIENT_ID"],\n'
        ")\n"
        "\n"
        "# 1. Authorize: PKCE S256 + RFC 8707 resource audience selector.\n"
        'pair = create_pkce_pair()  # (verifier, challenge, method="S256")\n'
        "authorize_url = auth.build_authorize_url(\n"
        '    redirect_uri="https://my-app.example/callback",\n'
        "    code_challenge=pair.challenge,\n"
        '    audience="tempo",\n'
        '    scope=["trace:read", "trace:write"],\n'
        ")\n"
        "\n"
        "# 2. Exchange the returned code for the audience's token set.\n"
        "auth.exchange_code(\n"
        "    code=code,\n"
        "    code_verifier=pair.verifier,\n"
        '    redirect_uri="https://my-app.example/callback",\n'
        '    audience="tempo",\n'
        ")\n"
        "\n"
        "# 3. Refresh with rotation: the new refresh token replaces the old one.\n"
        'auth.refresh("tempo")\n'
        "\n"
        "# 4. Revoke and drop the stored token set.\n"
        'auth.revoke("tempo")'
    )
    rust_code = (
        "use tempera_sdk::{AuthorizeUrlParams, TemperaAuth, pkce_pair_from_entropy};\n"
        "\n"
        "// The crate is HTTP-less: it builds the URLs and form bodies; you POST them\n"
        "// (content-type: application/x-www-form-urlencoded) with your HTTP client.\n"
        'let issuer_url = std::env::var("TEMPERA_ISSUER_URL")?;\n'
        'let client_id = std::env::var("TEMPERA_CLIENT_ID")?;\n'
        "let mut auth = TemperaAuth::new(issuer_url).with_client_id(client_id.clone());\n"
        "\n"
        "// 1. Authorize: PKCE S256 + RFC 8707 resource audience selector.\n"
        "let pkce = pkce_pair_from_entropy(&entropy); // >= 32 cryptographically random bytes\n"
        "let authorize_url = auth.authorize_url(&AuthorizeUrlParams {\n"
        "    client_id: &client_id,\n"
        '    redirect_uri: "https://my-app.example/callback",\n'
        "    code_challenge: &pkce.challenge,\n"
        '    audience: "tempo",\n'
        '    scope: Some("trace:read trace:write"),\n'
        "    state: None,\n"
        "});\n"
        "\n"
        "// 2. Exchange: POST this body at auth.token_url(), then store the response.\n"
        "let body = auth.code_exchange_body(\n"
        "    &code,\n"
        "    &pkce.verifier,\n"
        '    "https://my-app.example/callback",\n'
        '    "tempo",\n'
        ");\n"
        "// Refresh-token rotation is applied when you store the parsed response:\n"
        'auth.apply_token_response("tempo", access_token, Some(refresh_token));\n'
        "\n"
        "// 3. Refresh: POST this body at auth.token_url().\n"
        'let refresh_form = auth.refresh_body("tempo");\n'
        "\n"
        "// 4. Revoke: POST this body at auth.revoke_url(); the stored set is dropped.\n"
        'let revoke_form = auth.revoke_body("tempo");'
    )
    lines += code_group(
        [
            ("typescript", "TypeScript", ts_code),
            ("python", "Python", py_code),
            ("rust", "Rust", rust_code),
        ]
    )
    lines += [
        "## tp_ API keys: universal bearers",
        "",
        "Workspace API keys minted by the control plane (`createApiKey`, secrets",
        "prefixed `tp_`) are **universal bearers**: every product accepts them via",
        "central introspection, so one key covers every audience. Give `TemperaAuth`",
        "an `apiKey` / `api_key` / `with_api_key(...)` and skip the OAuth flow",
        "entirely for headless use.",
        "",
        "## Bearer resolution order",
        "",
        "For each call, the client resolves the bearer in this order:",
        "",
        "1. An explicit per-call `bearer` option, when you pass one.",
        "2. Per the operation's auth kind:",
        "   - `none` — no `authorization` header is sent.",
        "   - `account` — the account-session token stored by `login`/`signup` (or",
        "     passed as `accountToken` / `account_token` / `with_account_token`).",
        "   - `introspectionSecret` — the configured introspection secret",
        "     (`introspectToken` only; server-side).",
        "   - `product` — through `TemperaAuth.bearerFor(audience)`: the audience's",
        "     **access token** if one is stored, else the unified **`tp_` API key**,",
        "     else a configuration error before any request is sent.",
        "",
        "## Audiences",
        "",
        f"The registered token audiences (RFC 8707 `resource` values). `{surface['defaultAudience']}`",
        "is the default when none is specified.",
        "",
        "| Audience | Used by |",
        "|---|---|",
    ]
    audience_users: dict[str, list[str]] = {}
    for key, product in surface["products"].items():
        if product["audience"]:
            audience_users.setdefault(product["audience"], []).append(product["name"])
    for audience in surface["audiences"]:
        if audience == "tempera-mcp":
            used_by = "the unified [MCP gateway](/mcp-gateway)"
        else:
            used_by = ", ".join(sorted(audience_users.get(audience, []))) or "—"
        default = " (default)" if audience == surface["defaultAudience"] else ""
        lines.append(f"| `{audience}`{default} | {used_by} |")
    lines += [
        "",
        "## Scopes",
        "",
        "| Scope | Used by |",
        "|---|---|",
    ]
    scope_ops: dict[str, dict[str, list[str]]] = {}
    for product_key, ops in surface["operations"].items():
        for op in ops:
            if op.get("scope"):
                scope_ops.setdefault(op["scope"], {}).setdefault(product_key, []).append(op["id"])
    for scope in surface["scopes"]:
        if scope == "mcp:invoke":
            used_by = "the [MCP gateway](/mcp-gateway) — required for every tool call."
        elif scope == "pii:unmask":
            used_by = (
                "palette PII unmasking — pass `unmask` + `reason` on trace/span reads "
                "(`getTrace`, `getSpan`, `getSpanIo`)."
            )
        elif scope in scope_ops:
            parts = []
            for product_key in sorted(scope_ops[scope]):
                op_ids = ", ".join(f"`{op_id}`" for op_id in sorted(scope_ops[scope][product_key]))
                parts.append(f"{surface['products'][product_key]['name']}: {op_ids}")
            used_by = "; ".join(parts)
        else:
            used_by = "No typed SDK operation declares it yet; enforced server-side."
        lines.append(f"| `{scope}` | {used_by} |")
    lines += [
        "",
        "## Issuer endpoints",
        "",
        "| Endpoint | Path |",
        "|---|---|",
    ]
    for label, key in sorted(
        [
            ("Authorize", "authorizePath"),
            ("Token", "tokenPath"),
            ("Revoke", "revokePath"),
            ("Introspect", "introspectPath"),
            ("MCP gateway", "mcpPath"),
        ]
    ):
        lines.append(f"| {label} | `{issuer[key]}` |")
    lines.append("")
    return "\n".join(lines)


def render_environments(surface: dict) -> str:
    lines = [
        frontmatter(
            "Environments",
            "The four environment presets, per-product base-URL env vars, and resolution precedence.",
        )
    ]
    env_names = list(surface["environments"])
    fields = sorted(next(iter(surface["environments"].values())))
    lines += private_access_note()
    lines += [
        "The SDK ships four versioned environment presets. A preset records target URLs;",
        "it does not assert that a deployment is live or generally available. Private",
        "onboarding tells you which preset and overrides to use. Begin with `staging`; use",
        "`production` only after Tempera explicitly provisions and approves production access.",
        "",
        "## Presets",
        "",
        "| Field | "
        + " | ".join(
            "`production` (reserved)" if name == "production" else f"`{name}`"
            for name in env_names
        )
        + " |",
        "|---|" + "---|" * len(env_names),
    ]
    for field in fields:
        row = [f"`{field}`"] + [f"`{surface['environments'][name][field]}`" for name in env_names]
        lines.append("| " + " | ".join(row) + " |")
    lines += [
        "",
        "## Per-product base-URL env vars",
        "",
        "Every product has a `TEMPERA_*_URL` environment variable, and only the",
        "control plane, palette, and tempo have preset URLs — the other products",
        "must get their base URL from the env var or an explicit override.",
        "",
        "| Product | Env var | Preset field |",
        "|---|---|---|",
    ]
    preset_fields = {"controlPlane": "controlPlaneUrl", "palette": "paletteApiUrl", "tempo": "tempoApiUrl"}
    for key, product in surface["products"].items():
        preset = f"`{preset_fields[key]}`" if key in preset_fields else "—"
        lines.append(f"| {product['name']} | `{product['envVar']}` | {preset} |")
    lines += [
        "",
        "## Base-URL precedence",
        "",
        "For each product, the client resolves the base URL in this order (first hit",
        "wins); if nothing resolves, calls fail with a configuration error before any",
        "request is sent:",
        "",
        "1. **Explicit override** — `baseUrls.<product>` (TypeScript),",
        "   `base_urls[\"<product>\"]` (Python), or `with_base_url(\"<product>\", url)` (Rust).",
        "2. **The product's env var** — `TEMPERA_*_URL` from the table above.",
        "3. **The environment preset** — TypeScript and Python only, and only for the",
        "   control plane, palette, and tempo. The Rust crate takes no `environment`",
        "   option; use an explicit `with_base_url` or the env var (the preset table is",
        "   still available as `tempera_sdk::ENVIRONMENTS`).",
        "",
        "Trailing slashes on configured base URLs are trimmed in every language.",
        "",
    ]
    return "\n".join(lines)


def render_errors(surface: dict) -> str:
    contract = surface["errorContract"]
    lines = [
        frontmatter(
            "Errors",
            "One TemperaApiError across six wire error shapes, plus MCP gateway errors.",
        )
    ]
    lines += [
        "Every product speaks its own wire error shape; the SDK normalizes all of",
        f"them into one **`{contract['name']}`** with identical fields in every",
        "language (Python uses `request_id`; the HTTP-less Rust crate normalizes",
        "`status`/`code`/`message`/`request_id` from response bodies via",
        "`normalize_error_body` and carries no request context):",
        "",
        "| Field | Meaning |",
        "|---|---|",
    ]
    field_meanings = {
        "status": "HTTP status code of the failed response.",
        "code": "Machine-readable error code, when the wire shape carried one (else null/None).",
        "message": "Human-readable error message; never empty.",
        "requestId": "Server request id, from the body or the `x-request-id` response header.",
        "product": "Product key of the client that made the call.",
        "operation": "Operation id of the typed call (null/None for passthrough requests).",
        "body": "The raw parsed response body, untouched.",
    }
    for field in contract["fields"]:
        lines.append(f"| `{field}` | {cell(field_meanings.get(field, ''))} |")
    lines += [
        "",
        "## Normalization rules",
        "",
        "Applied in order to the parsed error body:",
        "",
    ]
    for index, rule in enumerate(contract["normalization"], start=1):
        lines.append(f"{index}. {esc(rule)}")
    lines += [
        "",
        "## Wire shapes by product",
        "",
        "| Product | Wire error shape |",
        "|---|---|",
    ]
    for product_key, shape in contract["wireShapes"].items():
        name = surface["products"][product_key]["name"]
        lines.append(f"| {name} | `{shape}` |")
    lines += [
        "",
        "## TemperaMcpError",
        "",
        "JSON-RPC errors from the [MCP gateway](/mcp-gateway) raise `TemperaMcpError`",
        "(TypeScript and Python) with the gateway's integer `code`, its `message`, and",
        "any `data` member. The Rust crate returns the same information as `McpError`",
        "(`code`, `message`) from `parse_mcp_error(body)`. A non-conformant error",
        "without an integer code is reported uniformly as code `0`.",
        "",
        "## MCP gateway error codes",
        "",
        "| Name | Code | Meaning |",
        "|---|---|---|",
    ]
    for name, code in surface["mcpGateway"]["errorCodes"].items():
        lines.append(f"| `{name}` | `{code}` | {MCP_ERROR_MEANINGS.get(name, '')} |")
    lines.append("")
    return "\n".join(lines)


def render_mcp_gateway(surface: dict) -> str:
    gateway = surface["mcpGateway"]
    lines = [
        frontmatter(
            "MCP gateway",
            "The unified MCP gateway: every product's tools behind one JSON-RPC endpoint.",
        )
    ]
    lines += private_access_note()
    lines += [
        "The unified MCP gateway lives at **`${issuer}/mcp`**, using the issuer URL",
        "supplied during onboarding. It is a stateless streamable-HTTP JSON-RPC 2.0 endpoint.",
        "It requires a bearer minted for audience **`tempera-mcp`** with scope",
        "**`mcp:invoke`** — or a central `tp_` API key.",
        "",
        "The gateway aggregates every product MCP server behind **namespaced tools**",
        "(`palette_*`, `tempo_*`, `cradle_*`, `remi_*`, `data_engine_*`), so one endpoint and one",
        "credential expose the whole fleet. Product tool calls are metered as",
        "`mcp_invocations` against the workspace's plan.",
        "",
        "## JSON-RPC methods",
        "",
        "| Method | JSON-RPC | Tool | Description |",
        "|---|---|---|---|",
    ]
    for method in gateway["methods"]:
        tool = f"`{method['tool']}`" if method.get("tool") else "—"
        lines.append(f"| `{method['id']}` | `{method['rpc']}` | {tool} | {cell(method['description'])} |")
    builtin_tools = [method for method in gateway["methods"] if method.get("tool")]
    lines += [
        "",
        "## Builtin tools",
        "",
        "Alongside the namespaced product tools, the gateway serves its own builtins",
        "(not metered as product invocations):",
        "",
    ]
    for method in builtin_tools:
        lines.append(f"- **`{method['tool']}`** — {esc(method['description'])}")
    lines += [
        "",
        "## Plan-limit errors",
        "",
        "When the workspace exhausts its metered `mcp_invocations` allowance, tool",
        f"calls fail with JSON-RPC error code `{gateway['errorCodes']['planLimit']}`",
        "(`plan_limit_exceeded`). See the full [error-code table](/errors#mcp-gateway-error-codes).",
        "",
        "## Client examples",
        "",
        "TypeScript and Python ship a `TemperaMcpClient`; the HTTP-less Rust crate",
        "ships `McpRequestBuilder`, which produces the exact JSON-RPC bodies to POST",
        "at `TemperaAuth::mcp_url()`.",
        "",
    ]
    ts_code = (
        'import { TemperaAuth, TemperaMcpClient } from "@tempera/sdk";\n'
        "\n"
        "const issuerUrl = process.env.TEMPERA_ISSUER_URL;\n"
        'if (!issuerUrl) throw new Error("Missing TEMPERA_ISSUER_URL");\n'
        "const auth = new TemperaAuth({ issuerUrl, apiKey: process.env.TEMPERA_API_KEY });\n"
        "const mcp = new TemperaMcpClient({ auth }); // url derives as ${issuer}/mcp\n"
        "\n"
        "await mcp.initialize();\n"
        "const tools = await mcp.listTools();\n"
        'const result = await mcp.callTool("cradle_get_capabilities");\n'
        "console.log(await mcp.whoami());\n"
        "console.log(await mcp.status());"
    )
    py_code = (
        "import os\n"
        "from tempera_sdk import TemperaAuth, TemperaMcpClient\n"
        "\n"
        'auth = TemperaAuth(issuer_url=os.environ["TEMPERA_ISSUER_URL"], api_key=os.environ["TEMPERA_API_KEY"])\n'
        "mcp = TemperaMcpClient(auth=auth)  # url derives as ${issuer}/mcp\n"
        "\n"
        "mcp.initialize()\n"
        "tools = mcp.list_tools()\n"
        'result = mcp.call_tool("cradle_get_capabilities")\n'
        "print(mcp.whoami())\n"
        "print(mcp.status())"
    )
    rust_code = (
        "use tempera_sdk::{McpRequestBuilder, TemperaAuth, parse_mcp_error};\n"
        "\n"
        'let issuer_url = std::env::var("TEMPERA_ISSUER_URL")?;\n'
        "let auth = TemperaAuth::new(issuer_url).with_api_key(api_key);\n"
        "let mut mcp = McpRequestBuilder::new();\n"
        "\n"
        "// POST each body at auth.mcp_url() with the tempera-mcp bearer:\n"
        'let (id, body) = mcp.initialize_body("tempera-sdk", "0.3.0");\n'
        "let (id, body) = mcp.list_tools_body();\n"
        'let (id, body) = mcp.call_tool_body("cradle_get_capabilities", None);\n'
        "let (id, body) = mcp.whoami_body();\n"
        "\n"
        "// Feed error responses to the shared parser:\n"
        "if let Some(err) = parse_mcp_error(&response_body) {\n"
        '    eprintln!("MCP error {}: {}", err.code, err.message);\n'
        "}"
    )
    lines += code_group(
        [
            ("typescript", "TypeScript", ts_code),
            ("python", "Python", py_code),
            ("rust", "Rust", rust_code),
        ]
    )
    return "\n".join(lines)


def render_rollout(rollout_md: str) -> str:
    body = rollout_md.strip()
    title = "Rollout"
    match = re.match(r"^#\s+(.+)\n", body)
    if match:
        title = match.group(1).strip()
        body = body[match.end():].strip()
    lines = [
        frontmatter(
            title,
            "The endpoint-change rollout contract: how a product change lands in the SDK.",
        )
    ]
    lines += [
        "{/* This page is rendered verbatim from docs/ROLLOUT.md, which stays the",
        "    source of truth for the rollout process. Edit docs/ROLLOUT.md and rerun",
        "    python3 scripts/gen-sdk-docs.py. */}",
        "",
        body,
        "",
    ]
    return "\n".join(lines)


def render_product_page(surface: dict, product_key: str) -> str:
    product = surface["products"][product_key]
    ops = surface["operations"][product_key]
    rust_product = snake(product_key)
    audience_cell = f"`{product['audience']}`" if product["audience"] else "— (no OAuth audience)"
    lines = [frontmatter(product["name"], product["description"])]
    lines += private_access_note()
    lines += [
        esc(product["description"]),
        "",
        "| | |",
        "|---|---|",
        f"| Repository | [{product['repository'].rsplit('/', 1)[-1]}]({product['repository']}) |",
        f"| Base URL env var | `{product['envVar']}` (see [Environments](/environments)) |",
        f"| Audience | {audience_cell} |",
        f"| Auth | {cell(product['auth'])} |",
        f"| Client | TypeScript `client.{product_key}` · Python `client.{snake_attr(product_key)}` · "
        f'Rust `build_request("{rust_product}", ...)` |',
        f"| Typed operations | {len(ops)} |",
        "",
        "Anything this page does not cover is reachable through the raw passthrough:",
        f"`client.{product_key}.request(path, options)` (TypeScript) /",
        f"`client.{snake_attr(product_key)}.request(path, ...)` (Python).",
        "",
        "## Operations",
        "",
    ]
    for op in ops:
        lines += operation_section(surface, product_key, op)
    return "\n".join(lines)


def render_other_products(surface: dict) -> str:
    keys = registry_products(surface)
    lines = [
        frontmatter(
            "Other products",
            "Registry-only products: passthrough clients with no typed operations yet.",
        )
    ]
    lines += private_access_note()
    lines += [
        "These products are registered in `surface.json` but have **no typed",
        "operations yet**. They still get a full product client in every language —",
        "registry metadata, base-URL resolution, auth wiring, and the raw `request()`",
        "escape hatch — so a provisioned endpoint can be used before typed operations",
        "land once its HTTP contract is stable (see [Rollout](/rollout)).",
        "",
        "| Product | Audience | Env var | Repository | Description |",
        "|---|---|---|---|---|",
    ]
    for key in keys:
        product = surface["products"][key]
        audience = f"`{product['audience']}`" if product["audience"] else "—"
        repo = product["repository"]
        lines.append(
            f"| {product['name']} | {audience} | `{product['envVar']}` | "
            f"[{repo.rsplit('/', 1)[-1]}]({repo}) | {cell(product['description'])} |"
        )
    lines += [
        "",
        "## Client accessors",
        "",
        "| Product | TypeScript | Python | Rust registry key |",
        "|---|---|---|---|",
    ]
    for key in keys:
        product = surface["products"][key]
        lines.append(
            f"| {product['name']} | `client.{key}` | `client.{snake_attr(key)}` | `\"{snake(key)}\"` |"
        )
    lines += [
        "",
        "## Calling them: the request() escape hatch",
        "",
        "Every product client exposes a raw `request()` that resolves the product's",
        "base URL and bearer for you. Products with a registered audience (only",
        "`human-data` here) attach an audience token or `tp_` API key automatically;",
        "audience-less products send no bearer unless you pass one explicitly.",
        "",
    ]
    ts_code = (
        "// human-data has an audience: the bearer is attached automatically.\n"
        'const queues = await client.humanData.request("/v1/queues");\n'
        "\n"
        "// Audience-less products: pass a bearer (or headers) yourself if needed.\n"
        'await client.tempJs.request("/v1/runtimes", { method: "GET" });\n'
        'await client.tempOS.request("/v1/receipts", { bearer: myToken });\n'
        'await client.arrha.request("/v1/credits/balance", { query: { org_id: "org_1" } });'
    )
    py_code = (
        "# human-data has an audience: the bearer is attached automatically.\n"
        'queues = client.human_data.request("/v1/queues")\n'
        "\n"
        "# Audience-less products: pass a bearer (or headers) yourself if needed.\n"
        'client.temp_js.request("/v1/runtimes", method="GET")\n'
        'client.temp_os.request("/v1/receipts", bearer=my_token)\n'
        'client.arrha.request("/v1/credits/balance", query={"org_id": "org_1"})'
    )
    rust_code = (
        "// The Rust crate has no passthrough request builder; typed operations only.\n"
        "// For registry-only products, read the registry and build the request yourself:\n"
        'use tempera_sdk::{TemperaAuth, find_product};\n'
        "\n"
        'let product = find_product("human_data").unwrap();\n'
        "let base_url = std::env::var(product.env_var)?; // TEMPERA_HUMAN_DATA_URL\n"
        'let issuer_url = std::env::var("TEMPERA_ISSUER_URL")?;\n'
        "let auth = TemperaAuth::new(issuer_url).with_api_key(api_key);\n"
        "let bearer = product.audience.and_then(|aud| auth.bearer_for(aud));\n"
        '// GET {base_url}/v1/queues with "authorization: Bearer <bearer>".'
    )
    lines += code_group(
        [
            ("typescript", "TypeScript", ts_code),
            ("python", "Python", py_code),
            ("rust", "Rust", rust_code),
        ]
    )
    return "\n".join(lines)


def render_site(surface: dict, rollout_md: str) -> dict[str, str]:
    """Render every file of the site, keyed by path relative to docs/site/."""
    files: dict[str, str] = {
        "docs.json": render_docs_json(surface),
        "index.mdx": render_index(surface),
        "authentication.mdx": render_authentication(surface),
        "environments.mdx": render_environments(surface),
        "errors.mdx": render_errors(surface),
        "mcp-gateway.mdx": render_mcp_gateway(surface),
        "rollout.mdx": render_rollout(rollout_md),
        "products/other-products.mdx": render_other_products(surface),
    }
    for product_key in typed_products(surface):
        files[f"{product_page_slug(product_key)}.mdx"] = render_product_page(surface, product_key)
    validate_site(surface, files)
    return files


def validate_site(surface: dict, files: dict[str, str]) -> None:
    """Sanity checks: docs.json parses, every navigation page has a file, and
    every operation in the manifest appears on its product page."""
    config = json.loads(files["docs.json"])
    nav_pages = [
        page for group in config["navigation"]["groups"] for page in group["pages"]
    ]
    for page in nav_pages:
        assert f"{page}.mdx" in files, f"navigation page {page!r} has no generated file"
    mdx_pages = {path[:-4] for path in files if path.endswith(".mdx")}
    assert sorted(nav_pages) == sorted(mdx_pages), (
        f"navigation and generated pages differ: {sorted(set(nav_pages) ^ mdx_pages)}"
    )
    for product_key, ops in surface["operations"].items():
        page = files[f"{product_page_slug(product_key)}.mdx"]
        for op in ops:
            assert f"### {op['id']}\n" in page, (
                f"operation {product_key}.{op['id']} missing from its product page"
            )
    forbidden_public_examples = [
        'issuerUrl: "https://api.tempera.dev"',
        'issuer_url="https://api.tempera.dev"',
        'TemperaAuth::new("https://api.tempera.dev")',
        'environment: "production"',
        'environment="production"',
    ]
    for path, content in files.items():
        if path == "environments.mdx":
            continue  # The reserved production target remains part of the reference contract.
        for forbidden in forbidden_public_examples:
            assert forbidden not in content, (
                f"{path}: public example presents reserved production access: {forbidden!r}"
            )
    for path, content in files.items():
        if path.endswith(".mdx"):
            assert GENERATED_NOTE in content, f"{path}: missing generated-by note"


def existing_site_files() -> list[Path]:
    if not SITE.exists():
        return []
    return sorted(path for path in SITE.rglob("*") if path.is_file())


def main() -> int:
    surface = json.loads(SURFACE.read_text())
    files = render_site(surface, ROLLOUT.read_text())
    check = "--check" in sys.argv

    if check:
        stale: list[str] = []
        for rel_path, rendered in sorted(files.items()):
            target = SITE / rel_path
            if not target.exists() or target.read_text() != rendered:
                stale.append(rel_path)
        expected = {SITE / rel_path for rel_path in files}
        for path in existing_site_files():
            if path not in expected:
                stale.append(f"{path.relative_to(SITE)} (stray file not produced by the generator)")
        if stale:
            for rel_path in stale:
                print(
                    f"stale generated docs: docs/site/{rel_path} (run python3 scripts/gen-sdk-docs.py)",
                    file=sys.stderr,
                )
            return 1
        print(f"generated docs site is current ({len(files)} files)")
        return 0

    expected = {SITE / rel_path for rel_path in files}
    for path in existing_site_files():
        if path not in expected:
            path.unlink()
            print(f"removed stray docs/site/{path.relative_to(SITE)}")
    for rel_path, rendered in sorted(files.items()):
        target = SITE / rel_path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(rendered)
        print(f"wrote docs/site/{rel_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
