#!/usr/bin/env python3
"""Verify narrow exact-source ledger removals without executing PR code.

This program is intentionally used only by the base-owned
``pull_request_target`` workflow.  It treats a pull request as an untrusted
Git tree: it never checks it out, imports it, reads its workflow files, or
executes any file from it.  The only candidate content it reads is the fixed
set of source locks, generated contract files, and the gap ledger below.

The workflow invokes ``validate`` before the Contract Reader token exists.
``validate`` writes a small trusted manifest containing only parsed values.
``verify`` subsequently obtains each source from a fixed GitHub URL with a
transient authentication header and compares its current ``main`` tree to
the candidate lock and generated bytes.  A gap may therefore be removed only
after the exact product named by that deletion was independently verified.
"""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any


SHA1_RE = re.compile(r"[0-9a-f]{40}\Z")
SHA256_RE = re.compile(r"[0-9a-f]{64}\Z")
LOCK_MAX_BYTES = 16 * 1024
GENERATED_MAX_BYTES = 2 * 1024 * 1024
LEDGER_MAX_BYTES = 256 * 1024
MANIFEST_SCHEMA_VERSION = 1

GAP_LEDGER_PATH = "contracts/sdk-exact-source-gaps.json"
LOCK_KEYS = {
    "schema_version",
    "source_repo",
    "source_branch",
    "source_commit",
    "source_path",
    "source_blob_sha",
    "source_mode",
    "source_sha256",
    "generated_with",
    "generated_path",
    "generated_sha256",
}
GAP_KEYS = {
    "repository",
    "source_commit",
    "blocker",
    "owner",
    "remediation",
    "producer_ci_url",
    "review_after",
}

# This is deliberately a static map in trusted base code.  Candidate locks can
# choose only a commit and hashes for their own product; they cannot choose a
# repository, branch, path, transform, or command to run.
PRODUCTS: dict[str, dict[str, str]] = {
    "temperaBio": {
        "repository": "tempera-dev/tempera-bio",
        "source_branch": "main",
        "source_path": "openapi/tempera-bio-discovery-v1.openapi.json",
        "lock_path": "specs/tempera-bio-api.json.source",
        "generated_path": "specs/tempera-bio-api.json",
        "generated_with": "source_lock.py@1+verbatim-openapi-copy",
    },
    "humanData": {
        "repository": "tempera-dev/human-data",
        "source_branch": "main",
        "source_path": "api/openapi.json",
        "lock_path": "specs/human-data-openapi.json.source",
        "generated_path": "specs/human-data-openapi.json",
        "generated_with": "source_lock.py@1+verbatim-openapi-copy",
    },
    "remi": {
        "repository": "tempera-dev/remi",
        "source_branch": "main",
        "source_path": "docs/public-http-contract.json",
        "lock_path": "specs/remi-http-contract.json.source",
        "generated_path": "specs/remi-http-contract.json",
        "generated_with": "sync-vendored-openapi.py@1+verbatim-contract-copy",
    },
    "tempo": {
        "repository": "tempera-dev/tempo",
        "source_branch": "main",
        "source_path": "api/openapi.json",
        "lock_path": "specs/tempo-openapi.json.source",
        "generated_path": "specs/tempo-openapi.json",
        "generated_with": "sync-vendored-openapi.py@1+verbatim-openapi-copy",
    },
}
PRODUCT_BY_REPOSITORY = {
    product["repository"]: name for name, product in PRODUCTS.items()
}


class VerificationError(ValueError):
    """A candidate or exact source fails this fail-closed gate."""


def git(repo: Path, *args: str, env: dict[str, str] | None = None) -> bytes:
    completed = subprocess.run(
        ["git", "-C", str(repo), *args],
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=env,
    )
    if completed.returncode:
        message = completed.stderr.decode("utf-8", errors="replace").strip()
        raise VerificationError(f"git {' '.join(args[:2])} failed: {message}")
    return completed.stdout


def commit_id(repo: Path, revision: str) -> str:
    value = git(repo, "rev-parse", "--verify", f"{revision}^{{commit}}")
    commit = value.decode("ascii").strip()
    if SHA1_RE.fullmatch(commit) is None:
        raise VerificationError(f"{revision!r} did not resolve to a lowercase SHA")
    return commit


def read_regular_blob(repo: Path, revision: str, path: str, maximum: int) -> bytes:
    """Read one bounded regular Git blob without checking out its tree."""

    if Path(path).is_absolute() or ".." in Path(path).parts:
        raise VerificationError(f"unsafe static path {path!r}")
    listing = git(repo, "ls-tree", "-z", revision, "--", path)
    expected_suffix = path.encode("utf-8") + b"\0"
    if not listing.endswith(expected_suffix):
        raise VerificationError(f"candidate is missing required path {path}")
    record = listing[:-1]
    if b"\0" in record or b"\t" not in record:
        raise VerificationError(f"invalid tree entry for {path}")
    metadata, listed_path = record.split(b"\t", 1)
    if listed_path != path.encode("utf-8"):
        raise VerificationError(f"unexpected tree path for {path}")
    fields = metadata.split()
    if len(fields) != 3 or fields[0] != b"100644" or fields[1] != b"blob":
        raise VerificationError(f"{path} must be a regular 100644 blob")
    blob = fields[2].decode("ascii", errors="strict")
    if SHA1_RE.fullmatch(blob) is None:
        raise VerificationError(f"invalid blob id for {path}")
    size_text = git(repo, "cat-file", "-s", blob).decode("ascii").strip()
    try:
        size = int(size_text)
    except ValueError as error:
        raise VerificationError(f"invalid blob size for {path}") from error
    if size < 0 or size > maximum:
        raise VerificationError(f"{path} exceeds the {maximum}-byte input limit")
    content = git(repo, "cat-file", "blob", blob)
    if len(content) != size:
        raise VerificationError(f"short read for {path}")
    return content


def parse_json(content: bytes, label: str) -> Any:
    try:
        return json.loads(content.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as error:
        raise VerificationError(f"{label} is not valid UTF-8 JSON") from error


def require_sha(value: Any, label: str, pattern: re.Pattern[str]) -> str:
    if not isinstance(value, str) or pattern.fullmatch(value) is None:
        raise VerificationError(f"{label} is not a lowercase fixed-length SHA")
    return value


def sha256(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def parse_ledger(content: bytes, label: str) -> dict[str, dict[str, str]]:
    ledger = parse_json(content, label)
    if (
        not isinstance(ledger, dict)
        or set(ledger) != {"schema_version", "gaps"}
        or ledger.get("schema_version") != 1
    ):
        raise VerificationError(f"{label} has an unsupported schema")
    gaps = ledger.get("gaps")
    if not isinstance(gaps, list):
        raise VerificationError(f"{label} gaps must be an array")
    indexed: dict[str, dict[str, str]] = {}
    for position, gap in enumerate(gaps):
        if not isinstance(gap, dict) or set(gap) != GAP_KEYS:
            raise VerificationError(f"{label} gaps[{position}] has unexpected keys")
        if not all(isinstance(gap[key], str) and gap[key] for key in GAP_KEYS):
            raise VerificationError(f"{label} gaps[{position}] has an empty value")
        repository = gap["repository"]
        if repository in indexed:
            raise VerificationError(f"{label} has duplicate repository {repository}")
        require_sha(gap["source_commit"], f"{label} {repository} source_commit", SHA1_RE)
        indexed[repository] = dict(gap)
    return indexed


def parse_lock(content: bytes, product_name: str) -> dict[str, str]:
    product = PRODUCTS[product_name]
    lock = parse_json(content, f"candidate {product['lock_path']}")
    if not isinstance(lock, dict) or set(lock) != LOCK_KEYS:
        raise VerificationError(f"candidate {product['lock_path']} has unexpected keys")
    if not all(isinstance(lock[key], (str, int)) for key in LOCK_KEYS):
        raise VerificationError(f"candidate {product['lock_path']} has invalid values")
    if lock.get("schema_version") != 1:
        raise VerificationError(f"candidate {product['lock_path']} has unsupported schema")
    for key in ("source_repo", "source_branch", "source_path", "generated_path", "generated_with"):
        if lock.get(key) != product[key if key not in {"source_repo"} else "repository"]:
            expected_key = key if key != "source_repo" else "repository"
            raise VerificationError(
                f"candidate {product['lock_path']} has non-allowlisted {key}: "
                f"expected {product[expected_key]!r}"
            )
    if lock.get("source_mode") != "100644":
        raise VerificationError(f"candidate {product['lock_path']} must lock mode 100644")
    for key, pattern in (
        ("source_commit", SHA1_RE),
        ("source_blob_sha", SHA1_RE),
        ("source_sha256", SHA256_RE),
        ("generated_sha256", SHA256_RE),
    ):
        require_sha(lock.get(key), f"candidate {product['lock_path']} {key}", pattern)
    return {key: str(value) for key, value in lock.items()}


def validate_candidate(repo: Path, base_revision: str, candidate_revision: str) -> dict[str, Any]:
    """Return a manifest after inspecting only fixed, bounded candidate blobs."""

    base = commit_id(repo, base_revision)
    candidate = commit_id(repo, candidate_revision)
    try:
        git(repo, "merge-base", "--is-ancestor", base, candidate)
    except VerificationError as error:
        raise VerificationError("candidate commit is not based on the trusted base") from error

    base_ledger = parse_ledger(
        read_regular_blob(repo, base, GAP_LEDGER_PATH, LEDGER_MAX_BYTES),
        "trusted-base gap ledger",
    )
    candidate_ledger = parse_ledger(
        read_regular_blob(repo, candidate, GAP_LEDGER_PATH, LEDGER_MAX_BYTES),
        "candidate gap ledger",
    )
    added = set(candidate_ledger) - set(base_ledger)
    changed = {
        repository
        for repository in set(candidate_ledger) & set(base_ledger)
        if candidate_ledger[repository] != base_ledger[repository]
    }
    removed = set(base_ledger) - set(candidate_ledger)
    if added or changed:
        raise VerificationError(
            "candidate gap ledger may only remove exact existing entries; "
            f"added={sorted(added)}, changed={sorted(changed)}"
        )
    if not removed:
        raise VerificationError("candidate removes no exact-source gap entries")
    unsupported = removed - set(PRODUCT_BY_REPOSITORY)
    if unsupported:
        raise VerificationError(
            f"candidate removes entries outside the trusted product map: {sorted(unsupported)}"
        )

    verified: list[dict[str, str]] = []
    for repository in sorted(removed):
        product_name = PRODUCT_BY_REPOSITORY[repository]
        product = PRODUCTS[product_name]
        lock = parse_lock(
            read_regular_blob(repo, candidate, product["lock_path"], LOCK_MAX_BYTES),
            product_name,
        )
        generated = read_regular_blob(
            repo, candidate, product["generated_path"], GENERATED_MAX_BYTES
        )
        generated_digest = sha256(generated)
        if generated_digest != lock["generated_sha256"]:
            raise VerificationError(
                f"candidate {product['generated_path']} does not match its lock digest"
            )
        # All four current exemptions are verbatim source contracts.  Requiring
        # matching candidate bytes makes this gate reject a source lock whose
        # generated artifact was hand-edited or not regenerated.
        if lock["source_sha256"] != generated_digest:
            raise VerificationError(
                f"candidate {product['generated_path']} is not the verbatim locked source"
            )
        verified.append(
            {
                "product": product_name,
                "repository": repository,
                "source_branch": product["source_branch"],
                "source_path": product["source_path"],
                "source_commit": lock["source_commit"],
                "source_blob_sha": lock["source_blob_sha"],
                "source_sha256": lock["source_sha256"],
                "generated_path": product["generated_path"],
                "generated_sha256": lock["generated_sha256"],
            }
        )
    return {
        "schema_version": MANIFEST_SCHEMA_VERSION,
        "trusted_base_commit": base,
        "candidate_commit": candidate,
        "verified_products": verified,
    }


def write_manifest(path: Path, manifest: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() or path.is_symlink():
        raise VerificationError("trusted manifest path must not already exist")
    flags = os.O_WRONLY | os.O_CREAT | os.O_EXCL
    descriptor = os.open(path, flags, 0o600)
    with os.fdopen(descriptor, "w", encoding="utf-8") as output:
        json.dump(manifest, output, sort_keys=True)
        output.write("\n")


def load_manifest(path: Path) -> dict[str, Any]:
    if path.is_symlink() or not path.is_file():
        raise VerificationError("trusted manifest must be a regular file")
    if path.stat().st_size > LEDGER_MAX_BYTES:
        raise VerificationError("trusted manifest exceeds its size limit")
    manifest = parse_json(path.read_bytes(), "trusted manifest")
    if (
        not isinstance(manifest, dict)
        or set(manifest) != {"schema_version", "trusted_base_commit", "candidate_commit", "verified_products"}
        or manifest.get("schema_version") != MANIFEST_SCHEMA_VERSION
    ):
        raise VerificationError("trusted manifest has an unsupported schema")
    products = manifest.get("verified_products")
    if not isinstance(products, list) or not products:
        raise VerificationError("trusted manifest must name at least one product")
    for commit_key in ("trusted_base_commit", "candidate_commit"):
        require_sha(manifest.get(commit_key), commit_key, SHA1_RE)
    for product in products:
        if not isinstance(product, dict) or product.get("product") not in PRODUCTS:
            raise VerificationError("trusted manifest has an unknown product")
        expected = PRODUCTS[product["product"]]
        for key, expected_value in (
            ("repository", expected["repository"]),
            ("source_branch", expected["source_branch"]),
            ("source_path", expected["source_path"]),
            ("generated_path", expected["generated_path"]),
        ):
            if product.get(key) != expected_value:
                raise VerificationError(f"trusted manifest has non-allowlisted {key}")
        for key, pattern in (
            ("source_commit", SHA1_RE),
            ("source_blob_sha", SHA1_RE),
            ("source_sha256", SHA256_RE),
            ("generated_sha256", SHA256_RE),
        ):
            require_sha(product.get(key), f"trusted manifest {key}", pattern)
    return manifest


def selected_installation_repositories(manifest: dict[str, Any]) -> str:
    """Render the selected static app-installation repository names only."""

    selected: set[str] = set()
    for product in manifest["verified_products"]:
        repository = product["repository"]
        product_name = PRODUCT_BY_REPOSITORY.get(repository)
        if product_name != product["product"]:
            raise VerificationError("trusted manifest product/repository mismatch")
        selected.add(repository.removeprefix("tempera-dev/"))
    if not selected:
        raise VerificationError("trusted manifest selects no Contract Reader repositories")
    return ",".join(sorted(selected))


def source_environment(token: str) -> dict[str, str]:
    if not token:
        raise VerificationError("Contract Reader token is empty")
    encoded = base64.b64encode(f"x-access-token:{token}".encode("utf-8")).decode("ascii")
    environment = {
        key: value
        for key, value in os.environ.items()
        if key not in {"CONTRACT_READER_TOKEN", "GH_TOKEN", "GITHUB_TOKEN"}
        and not key.startswith("GIT_CONFIG_")
    }
    # The header exists only in the subprocess environment.  It is not written
    # to a clone, Git config, output, manifest, or the candidate tree.
    environment.update(
        {
            "GIT_CONFIG_COUNT": "1",
            "GIT_CONFIG_KEY_0": "http.https://github.com/.extraheader",
            "GIT_CONFIG_VALUE_0": f"AUTHORIZATION: basic {encoded}",
            "GIT_TERMINAL_PROMPT": "0",
        }
    )
    return environment


def fetch_source(repository: str, branch: str, destination: Path, token: str) -> None:
    """Fetch only the fixed source branch into an ephemeral, trusted checkout."""

    if repository not in PRODUCT_BY_REPOSITORY or branch != "main":
        raise VerificationError("refusing a non-allowlisted exact source")
    destination.mkdir(parents=True, exist_ok=False)
    git(destination, "init", "--bare")
    git(destination, "remote", "add", "origin", f"https://github.com/{repository}.git")
    git(
        destination,
        "fetch",
        "--no-tags",
        "--no-write-fetch-head",
        "origin",
        "+refs/heads/main:refs/trusted/main",
        env=source_environment(token),
    )


def verify_one_source(source_repo: Path, product: dict[str, str]) -> None:
    current = commit_id(source_repo, "refs/trusted/main")
    if current != product["source_commit"]:
        raise VerificationError(
            f"{product['repository']} main is {current}, not candidate lock {product['source_commit']}"
        )
    source = read_regular_blob(
        source_repo,
        current,
        product["source_path"],
        GENERATED_MAX_BYTES,
    )
    blob = git(
        source_repo, "rev-parse", f"{current}:{product['source_path']}"
    ).decode("ascii").strip()
    if blob != product["source_blob_sha"]:
        raise VerificationError(f"{product['repository']} source blob does not match candidate lock")
    digest = sha256(source)
    if digest != product["source_sha256"] or digest != product["generated_sha256"]:
        raise VerificationError(f"{product['repository']} source digest does not match candidate lock")


def verify_manifest(manifest: dict[str, Any], token: str) -> list[str]:
    verified: list[str] = []
    temp_root = Path(tempfile.mkdtemp(prefix="tempera-sdk-trusted-source-"))
    try:
        for product in manifest["verified_products"]:
            source_repo = temp_root / product["product"]
            fetch_source(product["repository"], product["source_branch"], source_repo, token)
            verify_one_source(source_repo, product)
            verified.append(product["repository"])
    finally:
        shutil.rmtree(temp_root, ignore_errors=True)
    return verified


def parse_arguments() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    validate = commands.add_parser("validate", help="validate untrusted PR data without credentials")
    validate.add_argument("--repo-dir", type=Path, required=True)
    validate.add_argument("--base-rev", required=True)
    validate.add_argument("--candidate-rev", required=True)
    validate.add_argument("--manifest", type=Path, required=True)
    verify = commands.add_parser("verify", help="verify trusted manifest against current exact sources")
    verify.add_argument("--manifest", type=Path, required=True)
    verify.add_argument("--token-env", required=True)
    repositories = commands.add_parser(
        "repositories", help="print the selected fixed Contract Reader repositories"
    )
    repositories.add_argument("--manifest", type=Path, required=True)
    return parser.parse_args()


def main() -> int:
    args = parse_arguments()
    try:
        if args.command == "validate":
            manifest = validate_candidate(
                args.repo_dir.resolve(), args.base_rev, args.candidate_rev
            )
            write_manifest(args.manifest, manifest)
            repositories = ", ".join(
                product["repository"] for product in manifest["verified_products"]
            )
            print(f"candidate static validation passed for: {repositories}")
            return 0
        manifest = load_manifest(args.manifest)
        if args.command == "repositories":
            print(selected_installation_repositories(manifest))
            return 0
        token = os.environ.get(args.token_env, "")
        verified = verify_manifest(manifest, token)
        print(f"exact current-source verification passed for: {', '.join(verified)}")
        return 0
    except (OSError, VerificationError) as error:
        print(f"trusted PR exact-source gate failed: {error}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
